#The initial configuration came from the article: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

sudo: required
dist: trusty

python:
  - "3.5"

env:
  global:
    #COVERITY_SCAN_TOKEN
    - secure: "OtVLkLQ+O18ZOxFCVTotdxWwxOqE0HcCh7LEguFPpPOp5KX9JsBrRdN8Hq689AK+GnQVuYVHkRPdiduYq8CUoLppZy0AMus7muJp2bdnotwufOIZ0r9lqzau9F4HKcdg8LBjyoHq2gnJZgNsSlrma9AGJ8nKBlVCsOJU/2DB0zJ0ufUR92otRsbKlF0TFXC2SARHYL1fgjoJBtwtKyUkHcn5/85EZjUeZGVvvRIA1oqFN2ksHv2QSevSb4auZgi8Gz4LdkQFfWa+SYDoguMYDZCkJRg4kP/ciuAxWfulroXUyAHOGvg29AwkK7hpnFCiGCxm+mOoDousBrJymuqdblwyTzy3d84i1QZQWEAaSROuPA/cpmSPHBvx+H/YTkmdPKXp46728I1wSILOclN1icWll9KhuiDMGY48e2Zmux5SKuLTjg1wzFNrVEwLeiGT7kExWXeKdPMRo/xmH2vPDlBUVrl2z12RRinpGLW0lgG70f5EJl0K30ArNXmFfFZ775nUBokc9nVgK/bjA9t2olRlOC3tzkhgZnDYp7N/AudKeOnpsWeZEQjf9p/o7SjvMvqgbGXL6kZ74n8Jkau1nKIB+9viplLpBInxEYyMSZ/9qFZf3roYmBVYRA8v6G6PsFagYnqp4vl1zGjiO49KEW1jEF56gWKRYuYHQOaebsI="
    #Compilers
    - CC=gcc-6
    - CXX=g++-6

#Disable the default Travis submodule behavior.
git:
  submodules: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - txt2man
    - doxygen
    - graphviz

  coverity_scan:
    project:
      name: vcdMaker
      version: v3.0
      description: Coverity Scan by Travis CI
    notification_email: vcdmaker@mail.com
    build_command_prepend: "cov-configure --comptype gcc --compiler g++-6 --template && cmake ."
    build_command: "make"
    branch_pattern: coverity_scan

# Blocklist - branches not to be built. RegEx is allowed.
branches:
  except:
  - r2_release

# Safelist - branches to be built.
branches:
  only:
  - master
  - v3_release
  - coverity_scan

before_script:
  - git submodule update --init --recursive
  - cd ./sources

script:
  - cmake -DUSE_STATIC_PUGIXML=ON -DCMAKE_BUILD_TYPE=Release .
  - VERBOSE=1 make
  - make check
